### ISSUE TITLE
lczxxx123/disreproduce docker does not exist

### ISSUE THREAD

**Issue by byshen** [lujiefsi/CrashTuner#2]
Hi, it seems the docker for reproducing the paper results has been deleted.  

Is it possible to update with a new docker image for reproducing the results? thanks a lot

**Comment by lujiefsi** [comment]
@lczxxx123 could you prepare a docker image and put it into tar? Then we can share it by Dropbox. @byshen we are on vacation now,  it will take a while .

**Comment by byshen** [comment]
Thanks!

**Comment by lujiefsi** [comment]
@lczxxx123 are you working on the tar？I do not see the link!

**Comment by lczxxx123** [comment]
To push a new tag to this repository,
docker push lczxxx123/disreproduce:tagname

**Comment by lczxxx123** [comment]
docker pull lczxxx123/disreproduce:v0.8.23

**Comment by byshen** [comment]
Thanks!!
